web:
  build: .
  ports:
    - "8000:80"
  volumes:
    - ./app/:/app
    - ./nginx/:/etc/nginx/sites-enabled
  links:
    - localhost

localhost:
  image: sameersbn/mysql
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=demo
   - DB_USER=demo
   - DB_PASS=demo