web:
  build: .
  ports:
    - "8000:80"
  volumes:
    - ./app/:/app
    - ./nginx/default.conf:/etc/nginx/sites-available/vhost.conf
  links:
    - db

db:
  image: sameersbn/mysql
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=demo
   - DB_USER=demo
   - DB_PASS=demo